#!/bin/bash
set -e

# Usage: ./build-openresty-win.sh <version> [arch]
# Run inside MSYS2 MINGW64 shell
#
# Delegates to OpenResty's own util/build-win32.sh and util/package-win32.sh
# for a build process that matches upstream's tested Windows configuration.

VERSION="${1:?Usage: $0 <version> [arch]}"
ARCH="${2:-x86_64}"

CACHE_DIR="${CACHE_DIR:-$(pwd)/cache}"
mkdir -p "$CACHE_DIR"

download() {
  local url="$1"
  local out="${2:-$(basename "$url")}"
  local cache_file="$CACHE_DIR/$out"
  if [ -f "$cache_file" ]; then
    echo "==> Cache hit: $cache_file"
    cp "$cache_file" "$out"
  else
    echo "==> Downloading $url"
    wget -q --show-progress "$url" -O "$cache_file" && cp "$cache_file" "$out"
  fi
}

# Check prerequisites
for cmd in wget zip unix2dos patch perl gcc make; do
  command -v "$cmd" >/dev/null 2>&1 || { echo "ERROR: $cmd is required"; exit 1; }
done

echo "==> Building OpenResty ${VERSION} for Windows (MSYS2)"

# Download and extract OpenResty source
download "https://openresty.org/download/openresty-${VERSION}.tar.gz"
tar xzf "openresty-${VERSION}.tar.gz"
cd "openresty-${VERSION}"

# Let upstream build script control parallelism
export JOBS="${JOBS:-$(nproc)}"

# Build using OpenResty's own Windows build script
echo "==> Applying platform patches"

# Fix 1: $OS returns 'cygwin' (not 'msys') under MSYS2 perl,
# causing Windows-specific LuaJIT DLL installation to be skipped.
sed -i "s/\\\$OS eq 'msys'/\\\$OS eq 'msys' || \\\$OS eq 'cygwin'/g" configure

# Fix 2: 'cmd /c' triggers MSYS2 path translation (/c -> C:\),
# popping up a visible cmd window. 'cmd //c' passes args literally.
sed -i "s|cmd /c '|cmd //c '|g" util/package-win32.sh

# Fix 3: Modern MSYS2 uses SJLJ exception handling for i686,
# producing libgcc_s_sjlj-1.dll instead of libgcc_s_dw2-1.dll.
# Use a glob to match either variant.
sed -i "s/libgcc_s_dw2-1\\.dll/libgcc_s_*-1.dll/g" util/package-win32.sh

echo "==> Running util/build-win32.sh"
bash util/build-win32.sh

# Package using OpenResty's own Windows packaging script
echo "==> Running util/package-win32.sh"
bash util/package-win32.sh

# Find the generated zip and rename to our convention
ZIPFILE=$(ls *.zip 2>/dev/null | head -1)
if [ -z "$ZIPFILE" ]; then
  echo "ERROR: No zip file generated by package-win32.sh"
  exit 1
fi

DIST="openresty-${VERSION}-windows-${ARCH}-msys2"
mv "$ZIPFILE" "../${DIST}.zip"
cd ..
sha256sum "${DIST}.zip" > "${DIST}.zip.sha256"

echo "==> Done: $(pwd)/${DIST}.zip"
