#!/bin/bash
set -e

# Usage: ./build-openresty-win.sh <version> [arch]
# Run inside MSYS2 MINGW64 shell
#
# Delegates to OpenResty's own util/build-win32.sh and util/package-win32.sh
# for a build process that matches upstream's tested Windows configuration.

VERSION="${1:?Usage: $0 <version> [arch]}"
ARCH="${2:-x86_64}"

# ngx_http_proxy_connect_module 版本。
PROXY_CONNECT_VER="${PROXY_CONNECT_VER:-v0.0.7}"
# GitHub archive tarball 的顶层目录会去掉 tag 名前导的 v（v0.0.7 -> 0.0.7）
PROXY_CONNECT_DIR="ngx_http_proxy_connect_module-${PROXY_CONNECT_VER#v}"

# 本脚本所在目录（patches/ 存放 nginx 1.31+ 的适配补丁）
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# 补丁选择（与 build-openresty.sh 相同）：
#   nginx >= 1.31（OpenResty 1.31.x+）：核心已内置 CONNECT 请求行解析，
#   需使用仓库 patches/ 下的适配补丁；
#   更早版本使用模块自带补丁（proxy_connect_rewrite_102101.patch）。
NGINX_VER="${VERSION%.*}"
if [ "$(printf '%s\n' "${NGINX_VER}" "1.31" | sort -V | head -1)" = "1.31" ]; then
    PROXY_CONNECT_PATCH="proxy_connect_1311.patch"
    PROXY_CONNECT_NEW_NGINX=1
else
    PROXY_CONNECT_PATCH="proxy_connect_rewrite_102101.patch"
    PROXY_CONNECT_NEW_NGINX=0
fi

CACHE_DIR="${CACHE_DIR:-$(pwd)/cache}"
mkdir -p "$CACHE_DIR"

download() {
  local url="$1"
  local out="${2:-$(basename "$url")}"
  local cache_file="$CACHE_DIR/$out"
  if [ -f "$cache_file" ]; then
    echo "==> Cache hit: $cache_file"
    cp "$cache_file" "$out"
  else
    echo "==> Downloading $url"
    wget -q --show-progress "$url" -O "$cache_file" && cp "$cache_file" "$out"
  fi
}

# Check prerequisites
for cmd in wget zip unzip unix2dos patch perl gcc make curl; do
  command -v "$cmd" >/dev/null 2>&1 || { echo "ERROR: $cmd is required"; exit 1; }
done

echo "==> Building OpenResty ${VERSION} for Windows (MSYS2)"

# Download and extract OpenResty source
download "https://openresty.org/download/openresty-${VERSION}.tar.gz"
tar xzf "openresty-${VERSION}.tar.gz"

# Download and extract ngx_http_proxy_connect_module (CONNECT method support)
download "https://github.com/chobits/ngx_http_proxy_connect_module/archive/refs/tags/${PROXY_CONNECT_VER}.tar.gz" \
  "proxy-connect-${PROXY_CONNECT_VER}.tar.gz"
tar xzf "proxy-connect-${PROXY_CONNECT_VER}.tar.gz"

cd "openresty-${VERSION}"

# Let upstream build script control parallelism
export JOBS="${JOBS:-$(nproc)}"

# Build using OpenResty's own Windows build script
echo "==> Applying platform patches"

# Fix 1: $OS returns 'cygwin' (not 'msys') under MSYS2 perl,
# causing Windows-specific LuaJIT DLL installation to be skipped.
sed -i "s/\\\$OS eq 'msys'/\\\$OS eq 'msys' || \\\$OS eq 'cygwin'/g" configure

# Fix 2: 'cmd /c' triggers MSYS2 path translation (/c -> C:\),
# popping up a visible cmd window. 'cmd //c' passes args literally.
sed -i "s|cmd /c '|cmd //c '|g" util/package-win32.sh

# Fix 3: Hardcoded /c/msys64/mingw32 doesn't match GitHub Actions
# MSYS2 install path. Use the MSYS2 mount /mingw32 instead.
sed -i "s#mingw32=/c/msys64/mingw32#mingw32=/mingw32#" util/package-win32.sh

# Fix 4: zlib.net returns 415 for plain HTTP wget requests.
# Use HTTPS instead.
sed -i "s#http://zlib.net/#https://zlib.net/#" util/build-win32.sh

# Fix 5: 集成 ngx_http_proxy_connect_module。
# 1) 给 configure 注入 --add-module（绝对路径，避免相对路径在 build/ 内解析错误）；
# 2) 在 make 之前调用 win-patch-apply.sh 给 nginx 核心和模块打补丁。
if [ "${PROXY_CONNECT_NEW_NGINX}" = "1" ]; then
  cat > win-patch-apply.sh <<EOF
#!/bin/bash
set -e
NGINX_SRC="\$(pwd)/\$(find build -maxdepth 1 -type d -name 'nginx-*' | head -1)"
echo "==> Patching nginx core at \${NGINX_SRC} (${PROXY_CONNECT_PATCH})"
patch -d "\${NGINX_SRC}" -p1 < "${SCRIPT_DIR}/patches/${PROXY_CONNECT_PATCH}" || exit 1
echo "==> Patching proxy_connect module for nginx 1.31+"
patch -d "\$(pwd)/../${PROXY_CONNECT_DIR}" -p1 < "${SCRIPT_DIR}/patches/proxy_connect_module_1311.patch" || exit 1
EOF
else
  cat > win-patch-apply.sh <<EOF
#!/bin/bash
set -e
NGINX_SRC="\$(pwd)/\$(find build -maxdepth 1 -type d -name 'nginx-*' | head -1)"
echo "==> Patching nginx core at \${NGINX_SRC} (${PROXY_CONNECT_PATCH})"
patch -d "\${NGINX_SRC}" -p1 < "\$(pwd)/../${PROXY_CONNECT_DIR}/patch/${PROXY_CONNECT_PATCH}" || exit 1
EOF
fi
chmod +x win-patch-apply.sh
# configure 参数注入 --add-module（绝对路径，避免相对路径在 build/ 内解析错误）。
# 匹配 --with-openssl=objs/lib/ 行（唯一），在其后追加 --add-module。
ADDON_DIR="$(pwd)/../${PROXY_CONNECT_DIR}"
export ADDON_DIR
perl -i -pe 'if (/^    --with-openssl=objs\/lib\/\$OPENSSL/) {
    $_ .= "    --add-module=\"$ENV{ADDON_DIR}\" \x5c\n";
}' util/build-win32.sh
# make 之前调用补丁脚本（匹配 make -j$JOBS 行，唯一）
perl -i -pe 'if (/^make -j\$JOBS/) {
    $_ = "bash win-patch-apply.sh || exit 1\n" . $_;
}' util/build-win32.sh

echo "==> Running util/build-win32.sh"
bash util/build-win32.sh

# Package using OpenResty's own Windows packaging script
echo "==> Running util/package-win32.sh"
bash util/package-win32.sh

# Find the generated zip and rename to our convention
ZIPFILE=$(find . -maxdepth 1 -name '*.zip' | head -1)
if [ -z "$ZIPFILE" ]; then
  echo "ERROR: No zip file generated by package-win32.sh"
  exit 1
fi

DIST="openresty-${VERSION}-windows-${ARCH}-msys2"
mv "$ZIPFILE" "../${DIST}.zip"
cd ..
sha256sum "${DIST}.zip" > "${DIST}.zip.sha256"

# ---------- 解包冒烟 ----------
# 解包 zip 产物再验证: 官方 win 包编译期 prefix 为空, nginx 以 cwd 为
# prefix, 天然便携。断言静态页 + Lua content (后者验证 LuaJIT 运行时加载)。
WPORT=18480
cleanup_smoke() { taskkill //F //IM nginx.exe >/dev/null 2>&1 || true; }
trap cleanup_smoke EXIT
echo "==> 解包冒烟验证 (静态 + Lua, 端口 $WPORT)"
VERIFY=".or-win-verify.$$"
rm -rf "$VERIFY"; mkdir "$VERIFY"
unzip -q "${DIST}.zip" -d "$VERIFY"
cd "$VERIFY"/$(ls "$VERIFY" | head -1)
cp conf/nginx.conf conf/nginx.conf.orig
cat > conf/nginx.conf <<EOF
worker_processes 1;
error_log logs/error.log warn;
pid logs/nginx.pid;
events { worker_connections 128; }
http {
  access_log off;
  server {
    listen 127.0.0.1:$WPORT;
    location = /s { default_type text/plain; return 200 "win-smoke-static-ok"; }
    location = /lua { default_type text/plain; content_by_lua_block { return "win-smoke-lua-ok" } }
  }
}
EOF
./nginx.exe -p .
READY=0
for _ in $(seq 1 50); do
  if curl -sf -o /dev/null "http://127.0.0.1:$WPORT/s" 2>/dev/null; then READY=1; break; fi
  sleep 0.2
done
if [ "$READY" != "1" ]; then
  echo "ERROR: nginx.exe did not become ready on port $WPORT" >&2
  cat logs/error.log >&2 || true
  exit 1
fi
body="$(curl -sf "http://127.0.0.1:$WPORT/s")"
[ "$body" = "win-smoke-static-ok" ] || { echo "ERROR: static assertion failed: $body" >&2; exit 1; }
body="$(curl -sf "http://127.0.0.1:$WPORT/lua")"
[ "$body" = "win-smoke-lua-ok" ] || { echo "ERROR: lua assertion failed: $body" >&2; exit 1; }
echo "==> 解包冒烟通过"
cd ../..
rm -rf "$VERIFY"
trap - EXIT

echo "==> Done: $(pwd)/${DIST}.zip"
